# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: priyakdey.com-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/priydey/dev/github.com/priyakdey/newsletter-subscription/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: priyakdey.com-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
